export const SAVE_USERNAME = 'SAVE_USERNAME';
export const  AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';

export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SIGNUP_FAIL = 'AUTH_SIGNUP_FAIL';